# Generated by Django 3.1.3 on 2020-11-13 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLocation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('report_time', models.DateTimeField()),
                ('requester', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('report_locations', models.ManyToManyField(related_name='reports', related_query_name='reports', to='Reports.ReportLocation')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='reports', to='Reports.reporttype')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_time'],
            },
        ),
    ]
