# Generated by Django 3.1.3 on 2020-11-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('Reports', '0002_auto_20201113_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlocation',
            old_name='id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='reporttype',
            old_name='id',
            new_name='pid',
        ),
    ]
